### ISSUE TITLE
Issue in modelplot.m

### ISSUE THREAD

**Issue by RGRJON002** [RGRJON002/PIFF#1]
Hi all,  a few issues with modelplot have been fixed:

1) I forgot to change the fixed xlim value for the histogram as it only displayed values between 0-2. This has been amended.

2) modelplot.m would display an error if you just in-putted the two .mat files with none of the additional arguments due to modelplot.m wanting units. I have now made it such that modelplot will just ignore units if you chose this functionality.

3) For the summary table, the title was fixed to "Dissolved concentration of iron". This has been changed.

**Comment by mvichi** [comment]
All  these issues have been fixed in the current release
