### ISSUE TITLE
Script/protocol to run all sections and create statistics

### ISSUE THREAD

**Issue by mvichi** [RGRJON002/PIFF#2]
Alessandro suggests to build a protocol to run across all sections and summarise the statistics in one big table. This can be done with another script that loops over the sections and collects the metrics.
Visualising the overall metrics can be tricky. The table is OK, but difficult to read. 
An option could be to use MDS, as I did in the 2009 paper. A graphical rep of how distant each section is from the data

**Comment by RGRJON002** [comment]
Hi Marcello,

have designed a script called FeMIP_MDS will should do the job. Once I have done the debugging, will upload it

**Comment by RGRJON002** [comment]
FeMIP_MDS.m is now available
